class Phonetic {
  final int phoneticID;
  final String phonetic;
  final int phoneticType;
  final String youtubeVideoId;
  final String description;
  final Map<String, String> example;

  Phonetic({
    required this.phoneticID,
    required this.phonetic,
    required this.phoneticType,
    required this.youtubeVideoId,
    required this.description,
    required this.example,
  });

  factory Phonetic.initial() => Phonetic(
        phoneticID: 0,
        phonetic: '',
        phoneticType: 0,
        youtubeVideoId: '',
        description: '',
        example: {},
      );
}

final List<Phonetic> phoneticData = [
  Phonetic(
    phoneticID: 1,
    phonetic: "/ɪ/",
    phoneticType: 1,
    youtubeVideoId: "TNFKG0yvDx4",
    example: {"it": "/ɪt/", "sit": "/sɪt/", "ship": "/ʃɪp/"},
    description:
        "Âm 'i' ngắn phát âm giống âm 'i' của tiếng Việt nhưng phát âm nhanh hơn.",
  ),
  Phonetic(
    phoneticID: 2,
    phonetic: "/ʊ/",
    phoneticType: 1,
    youtubeVideoId: "eJ7dM_LU9t4",
    example: {"look": "/lʊk/", "cook": "/kʊk/", "foot": "/fʊt/"},
    description:
        "Âm 'u' ngắn, na ná âm 'ư' của tiếng Việt, không đứng riêng lẻ.",
  ),
  Phonetic(
    phoneticID: 3,
    phonetic: "/e/",
    phoneticType: 1,
    youtubeVideoId: "hLN1cdsTDo8",
    example: {"pen": "/pen/", "bed": "/bed/", "ten": "/ten/"},
    description: "Giống âm 'e' của tiếng Việt nhưng phát âm rất ngắn.",
  ),
  Phonetic(
    phoneticID: 4,
    phonetic: "/æ/",
    phoneticType: 1,
    youtubeVideoId: "wg0poYokniE",
    example: {"cat": "/kæt/", "dad": "/dæd/", "fat": "/fæt/"},
    description: "Âm 'a bẹt', hơi lai giữa âm 'a' và 'e', âm giác âm ở giữa.",
  ),
  Phonetic(
    phoneticID: 5,
    phonetic: "/ɑː/",
    phoneticType: 1,
    youtubeVideoId: "aBc0fK5gYkg",
    example: {"father": "/ˈfɑːðər/", "car": "/kɑːr/", "arm": "/ɑːrm/"},
    description: "Âm 'a' dài, phát âm trầm và giữ hơi lâu hơn.",
  ),
  Phonetic(
    phoneticID: 6,
    phonetic: "/ɔː/",
    phoneticType: 1,
    youtubeVideoId: "xFgP1DdFGz4",
    example: {"law": "/lɔː/", "saw": "/sɔː/", "thought": "/θɔːt/"},
    description: "Âm 'o' tròn và dài, môi mở rộng và phát âm sâu.",
  ),
  Phonetic(
    phoneticID: 7,
    phonetic: "/ʌ/",
    phoneticType: 1,
    youtubeVideoId: "Ud3ct5lMTzU",
    example: {"cup": "/kʌp/", "luck": "/lʌk/", "run": "/rʌn/"},
    description: "Giống âm 'â' của tiếng Việt, phát âm ngắn.",
  ),
  Phonetic(
    phoneticID: 8,
    phonetic: "/ɜː/",
    phoneticType: 1,
    youtubeVideoId: "eJ7M1v89Yz4",
    example: {"bird": "/bɜːd/", "word": "/wɜːd/", "girl": "/ɡɜːl/"},
    description: "Âm 'ơ' dài, âm thanh phát ra từ cổ họng, môi thả lỏng.",
  ),
  Phonetic(
    phoneticID: 9,
    phonetic: "/ə/",
    phoneticType: 1,
    youtubeVideoId: "PZ34s9pZeGU",
    example: {"sofa": "/ˈsəʊfə/", "banana": "/bəˈnænə/", "sugar": "/ˈʃʊɡə/"},
    description: "Âm 'ơ' ngắn, rất nhẹ, thường xuất hiện trong âm không nhấn.",
  ),
  Phonetic(
    phoneticID: 10,
    phonetic: "/iː/",
    phoneticType: 1,
    youtubeVideoId: "6Cp78_Rx6H0",
    example: {"see": "/siː/", "tree": "/triː/", "me": "/miː/"},
    description: "Giống âm 'i' dài, môi hơi cười, kéo dài âm thanh.",
  ),
  Phonetic(
    phoneticID: 11,
    phonetic: "/uː/",
    phoneticType: 1,
    youtubeVideoId: "7JtO8vgHhhM",
    example: {"food": "/fuːd/", "blue": "/bluː/", "two": "/tuː/"},
    description: "Giống âm 'u' dài, môi tròn và phát âm sâu.",
  ),
  Phonetic(
    phoneticID: 12,
    phonetic: "/b/",
    phoneticType: 1,
    youtubeVideoId: "4BQJFDH0NoY",
    example: {"bat": '/bæt/', 'cab': '/kæb/', 'table': '/ˈteɪbəl/'},
    description: "Đặt môi lại với nhau và phát âm ra âm 'b' ngắn.",
  ),
  Phonetic(
    phoneticID: 13,
    phonetic: "/d/",
    phoneticType: 1,
    youtubeVideoId: "NtZhT_t0ZJg",
    example: {'dog': '/dɔɡ/', 'sad': '/sæd/', 'bed': '/bɛd/'},
    description: "Đặt đầu lưỡi chạm vào răng trên, tạo âm 'd' ngắn.",
  ),
  Phonetic(
    phoneticID: 14,
    phonetic: "/f/",
    phoneticType: 1,
    youtubeVideoId: "fI8Z6pH6a_k",
    example: {'fish': '/fɪʃ/', 'safe': '/seɪf/', 'coffee': '/ˈkɒfi/'},
    description: "Đặt răng trên lên môi dưới, thổi ra để tạo âm 'f'.",
  ),
  Phonetic(
    phoneticID: 15,
    phonetic: "/g/",
    phoneticType: 1,
    youtubeVideoId: "zH_3nlnx6yQ",
    example: {'go': '/ɡoʊ/', 'flag': '/flæɡ/', 'big': '/bɪɡ/'},
    description: "Phát âm bằng cách tạo âm sâu trong cổ họng.",
  ),
  Phonetic(
    phoneticID: 16,
    phonetic: "/h/",
    phoneticType: 1,
    youtubeVideoId: "qYtY4dyZs60",
    example: {'hat': '/hæt/', 'home': '/hoʊm/', 'hello': '/həˈloʊ/'},
    description: "Âm thanh thoát ra từ cổ họng nhẹ nhàng.",
  ),
  Phonetic(
    phoneticID: 17,
    phonetic: "/j/",
    phoneticType: 1,
    youtubeVideoId: "LlZcdL7aQGg",
    example: {'yes': '/jɛs/', 'yellow': '/ˈjɛloʊ/', 'yard': '/jɑrd/'},
    description:
        "Âm 'j' tương tự âm 'y' trong tiếng Việt, phát âm từ vòm họng.",
  ),
  Phonetic(
    phoneticID: 18,
    phonetic: "/k/",
    phoneticType: 1,
    youtubeVideoId: "2u3e2qN7J_M",
    example: {'cat': '/kæt/', 'key': '/kiː/', 'back': '/bæk/'},
    description: "Tạo âm 'k' ngắn từ cổ họng, giống âm 'k' trong tiếng Việt.",
  ),
  Phonetic(
    phoneticID: 19,
    phonetic: "/l/",
    phoneticType: 1,
    youtubeVideoId: "mtNkBwO8f28",
    example: {'lamp': '/læmp/', 'call': '/kɔːl/', 'fall': '/fɔːl/'},
    description: "Âm 'l' phát ra khi đầu lưỡi chạm vào vòm miệng trên.",
  ),
  Phonetic(
    phoneticID: 20,
    phonetic: "/m/",
    phoneticType: 1,
    youtubeVideoId: "rH5qZLFJQlE",
    example: {'man': '/mæn/', 'home': '/hoʊm/', 'come': '/kʌm/'},
    description: "Đặt môi lại với nhau và tạo âm 'm' ngắn.",
  ),
  Phonetic(
    phoneticID: 21,
    phonetic: "/n/",
    phoneticType: 1,
    youtubeVideoId: "IgPj8a_MQAs",
    example: {'name': '/neɪm/', 'pen': '/pɛn/', 'ten': '/tɛn/'},
    description: "Âm 'n' ngắn, tạo âm thanh từ mũi.",
  ),
  Phonetic(
    phoneticID: 22,
    phonetic: "/ŋ/",
    phoneticType: 1,
    youtubeVideoId: "b0-a3Hqyb5E",
    example: {'sing': '/sɪŋ/', 'long': '/lɔːŋ/', 'ring': '/rɪŋ/'},
    description: "Tạo âm từ phía cuối lưỡi, giống âm 'ng' tiếng Việt.",
  ),
  Phonetic(
    phoneticID: 23,
    phonetic: "/p/",
    phoneticType: 2,
    youtubeVideoId: "WLU2VPZLrxg",
    example: {'pen': '/pɛn/', 'cap': '/kæp/', 'top': '/tɒp/'},
    description: "Đặt môi lại và đẩy không khí ra tạo âm 'p' ngắn.",
  ),
  Phonetic(
    phoneticID: 24,
    phonetic: "/r/",
    phoneticType: 2,
    youtubeVideoId: "jO43VhNo5XM",
    example: {'red': '/rɛd/', 'car': '/kɑːr/', 'road': '/roʊd/'},
    description: "Đặt lưỡi cong lên vòm miệng, tạo âm 'r'.",
  ),
  Phonetic(
    phoneticID: 25,
    phonetic: "/s/",
    phoneticType: 2,
    youtubeVideoId: "oGzjNo6nBFc",
    example: {'sun': '/sʌn/', 'pass': '/pæs/', 'bus': '/bʌs/'},
    description: "Đẩy không khí qua kẽ giữa răng tạo âm 's' xì.",
  ),
  Phonetic(
    phoneticID: 26,
    phonetic: "/t/",
    phoneticType: 2,
    youtubeVideoId: "rhPzqNkzArU",
    example: {'top': '/tɒp/', 'cat': '/kæt/', 'hat': '/hæt/'},
    description: "Đầu lưỡi chạm vào vòm miệng trên, tạo âm 't'.",
  ),
  Phonetic(
    phoneticID: 27,
    phonetic: "/v/",
    phoneticType: 2,
    youtubeVideoId: "OBd_uhU5ZQ0",
    example: {'van': '/væn/', 'love': '/lʌv/', 'have': '/hæv/'},
    description: "Đặt răng trên lên môi dưới, thổi ra để tạo âm 'v'.",
  ),
  Phonetic(
    phoneticID: 28,
    phonetic: "/w/",
    phoneticType: 2,
    youtubeVideoId: "xk_1d6cFTzY",
    example: {'we': '/wiː/', 'water': '/ˈwɔːtər/', 'win': '/wɪn/'},
    description: "Môi tròn, phát âm giống âm 'qu' trong tiếng Việt.",
  ),
  Phonetic(
    phoneticID: 29,
    phonetic: "/z/",
    phoneticType: 2,
    youtubeVideoId: "ID2MseolUV8",
    example: {'zoo': '/zuː/', 'buzz': '/bʌz/', 'lazy': '/ˈleɪzi/'},
    description: "Tạo âm 'z' rung nhẹ trong cổ họng và kéo dài.",
  ),
  Phonetic(
    phoneticID: 30,
    phonetic: "/θ/",
    phoneticType: 2,
    youtubeVideoId: "QaaFnSE8QdY",
    example: {'think': '/θɪŋk/', 'bath': '/bæθ/', 'tooth': '/tuːθ/'},
    description: "Đặt đầu lưỡi giữa hai răng, tạo âm 'th' nhẹ.",
  ),
  Phonetic(
    phoneticID: 31,
    phonetic: "/ð/",
    phoneticType: 2,
    youtubeVideoId: "Oj9gnxP1qzY",
    example: {'this': '/ðɪs/', 'breathe': '/briːð/', 'mother': '/ˈmʌðər/'},
    description: "Đặt đầu lưỡi giữa hai răng, tạo âm 'th' rung.",
  ),
  Phonetic(
    phoneticID: 32,
    phonetic: "/ʃ/",
    phoneticType: 2,
    youtubeVideoId: "tCx2wYR4pPU",
    example: {'she': '/ʃiː/', 'fish': '/fɪʃ/', 'wish': '/wɪʃ/'},
    description: "Đẩy không khí qua giữa răng và tạo âm 'sh'.",
  ),
  Phonetic(
    phoneticID: 33,
    phonetic: "/ʒ/",
    phoneticType: 2,
    youtubeVideoId: "5wb1Zw6FDaM",
    example: {
      'measure': '/ˈmɛʒər/',
      'treasure': '/ˈtrɛʒər/',
      'vision': '/ˈvɪʒən/'
    },
    description: "Giống âm 'gi' của tiếng Việt, phát âm từ giữa răng.",
  ),
  Phonetic(
    phoneticID: 34,
    phonetic: "/tʃ/",
    phoneticType: 2,
    youtubeVideoId: "O8_XsSwgMxY",
    example: {'chair': '/tʃɛər/', 'watch': '/wɒtʃ/', 'teacher': '/ˈtiːtʃər/'},
    description: "Tạo âm 'ch' giống tiếng Việt, đẩy mạnh không khí qua răng.",
  ),
  Phonetic(
    phoneticID: 35,
    phonetic: "/dʒ/",
    phoneticType: 2,
    youtubeVideoId: "v9bnj7Q1gPI",
    example: {'jump': '/dʒʌmp/', 'judge': '/dʒʌdʒ/', 'bridge': '/brɪdʒ/'},
    description: "Giống âm 'd' kết hợp âm 'ʒ', như 'dờ' trong tiếng Việt.",
  ),
  Phonetic(
    phoneticID: 36,
    phonetic: "/aɪ/",
    phoneticType: 2,
    youtubeVideoId: "kIoacBaWM0w",
    example: {'my': '/maɪ/', 'like': '/laɪk/', 'sky': '/skaɪ/'},
    description: "Âm đôi kết hợp 'a' và 'ɪ', phát âm nhanh.",
  ),
  Phonetic(
    phoneticID: 37,
    phonetic: "/aʊ/",
    phoneticType: 2,
    youtubeVideoId: "WT8QCtSbn18",
    example: {'now': '/naʊ/', 'down': '/daʊn/', 'how': '/haʊ/'},
    description: "Âm đôi giữa 'a' và 'u', môi tròn dần khi phát âm.",
  ),
  Phonetic(
    phoneticID: 38,
    phonetic: "/eɪ/",
    phoneticType: 2,
    youtubeVideoId: "70p1UbNZfF4",
    example: {'day': '/deɪ/', 'say': '/seɪ/', 'play': '/pleɪ/'},
    description: "Âm đôi giữa 'e' và 'ɪ', môi hơi mở.",
  ),
  Phonetic(
    phoneticID: 39,
    phonetic: "/oʊ/",
    phoneticType: 2,
    youtubeVideoId: "lnX6HAp5Z7U",
    example: {'go': '/ɡoʊ/', 'show': '/ʃoʊ/', 'low': '/loʊ/'},
    description: "Âm đôi giữa 'o' và 'ʊ', môi tròn dần khi phát âm.",
  ),
  Phonetic(
    phoneticID: 40,
    phonetic: "/ɔɪ/",
    phoneticType: 2,
    youtubeVideoId: "8Qj8q3M1y7s",
    example: {'boy': '/bɔɪ/', 'toy': '/tɔɪ/', 'enjoy': '/ɪnˈdʒɔɪ/'},
    description: "Âm đôi giữa 'ɔ' và 'ɪ', phát âm giống âm 'oi'.",
  ),
  Phonetic(
    phoneticID: 41,
    phonetic: "/ɪə/",
    phoneticType: 2,
    youtubeVideoId: "5jOaTEJ2XK4",
    example: {'here': '/hɪə/', 'near': '/nɪə/', 'dear': '/dɪə/'},
    description: "Âm đôi giữa 'ɪ' và 'ə', phát âm giống 'ia'.",
  ),
  Phonetic(
    phoneticID: 42,
    phonetic: "/eə/",
    phoneticType: 2,
    youtubeVideoId: "xg9F7pTgLJo",
    example: {'air': '/eə/', 'care': '/keə/', 'share': '/ʃeə/'},
    description: "Âm đôi giữa 'e' và 'ə', giống âm 'e' kéo dài.",
  ),
  Phonetic(
    phoneticID: 43,
    phonetic: "/ʊə/",
    phoneticType: 2,
    youtubeVideoId: "uhXH3SZtQls",
    example: {'sure': '/ʃʊə/', 'pure': '/pjʊə/', 'tour': '/tʊə/'},
    description: "Âm đôi giữa 'ʊ' và 'ə', môi hơi tròn.",
  ),
  Phonetic(
    phoneticID: 44,
    phonetic: "/əʊ/",
    phoneticType: 2,
    youtubeVideoId: "xn9-eMiNb2A",
    example: {'go': '/ɡəʊ/', 'no': '/nəʊ/', 'so': '/səʊ/'},
    description: "Âm đôi giữa 'ə' và 'ʊ', giống âm 'âu' trong tiếng Việt.",
  ),
];
